// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	"github.com/MarceloMPJR/gorreios-etiqueta/lib"

	mock "github.com/stretchr/testify/mock"
)

// CorreiosSigepService is an autogenerated mock type for the CorreiosSigepService type
type CorreiosSigepService struct {
	mock.Mock
}

// AtualizaPagamentoNaEntrega provides a mock function with given fields: AtualizaPagamentoNaEntrega
func (_m *CorreiosSigepService) AtualizaPagamentoNaEntrega(AtualizaPagamentoNaEntrega *lib.AtualizaPagamentoNaEntrega) (*lib.AtualizaPagamentoNaEntregaResponse, error) {
	ret := _m.Called(AtualizaPagamentoNaEntrega)

	var r0 *lib.AtualizaPagamentoNaEntregaResponse
	if rf, ok := ret.Get(0).(func(*lib.AtualizaPagamentoNaEntrega) *lib.AtualizaPagamentoNaEntregaResponse); ok {
		r0 = rf(AtualizaPagamentoNaEntrega)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.AtualizaPagamentoNaEntregaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.AtualizaPagamentoNaEntrega) error); ok {
		r1 = rf(AtualizaPagamentoNaEntrega)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AtualizaRemessaAgrupada provides a mock function with given fields: AtualizaRemessaAgrupada
func (_m *CorreiosSigepService) AtualizaRemessaAgrupada(AtualizaRemessaAgrupada *lib.AtualizaRemessaAgrupada) (*lib.AtualizaRemessaAgrupadaResponse, error) {
	ret := _m.Called(AtualizaRemessaAgrupada)

	var r0 *lib.AtualizaRemessaAgrupadaResponse
	if rf, ok := ret.Get(0).(func(*lib.AtualizaRemessaAgrupada) *lib.AtualizaRemessaAgrupadaResponse); ok {
		r0 = rf(AtualizaRemessaAgrupada)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.AtualizaRemessaAgrupadaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.AtualizaRemessaAgrupada) error); ok {
		r1 = rf(AtualizaRemessaAgrupada)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BloquearObjeto provides a mock function with given fields: BloquearObjeto
func (_m *CorreiosSigepService) BloquearObjeto(BloquearObjeto *lib.BloquearObjeto) (*lib.BloquearObjetoResponse, error) {
	ret := _m.Called(BloquearObjeto)

	var r0 *lib.BloquearObjetoResponse
	if rf, ok := ret.Get(0).(func(*lib.BloquearObjeto) *lib.BloquearObjetoResponse); ok {
		r0 = rf(BloquearObjeto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BloquearObjetoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BloquearObjeto) error); ok {
		r1 = rf(BloquearObjeto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaCliente provides a mock function with given fields: BuscaCliente
func (_m *CorreiosSigepService) BuscaCliente(BuscaCliente *lib.BuscaCliente) (*lib.BuscaClienteResponse, error) {
	ret := _m.Called(BuscaCliente)

	var r0 *lib.BuscaClienteResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaCliente) *lib.BuscaClienteResponse); ok {
		r0 = rf(BuscaCliente)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaClienteResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaCliente) error); ok {
		r1 = rf(BuscaCliente)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaContrato provides a mock function with given fields: BuscaContrato
func (_m *CorreiosSigepService) BuscaContrato(BuscaContrato *lib.BuscaContrato) (*lib.BuscaContratoResponse, error) {
	ret := _m.Called(BuscaContrato)

	var r0 *lib.BuscaContratoResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaContrato) *lib.BuscaContratoResponse); ok {
		r0 = rf(BuscaContrato)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaContratoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaContrato) error); ok {
		r1 = rf(BuscaContrato)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaDataAtual provides a mock function with given fields: BuscaDataAtual
func (_m *CorreiosSigepService) BuscaDataAtual(BuscaDataAtual *lib.BuscaDataAtual) (*lib.BuscaDataAtualResponse, error) {
	ret := _m.Called(BuscaDataAtual)

	var r0 *lib.BuscaDataAtualResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaDataAtual) *lib.BuscaDataAtualResponse); ok {
		r0 = rf(BuscaDataAtual)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaDataAtualResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaDataAtual) error); ok {
		r1 = rf(BuscaDataAtual)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaOpcoes provides a mock function with given fields: BuscaOpcoes
func (_m *CorreiosSigepService) BuscaOpcoes(BuscaOpcoes *lib.BuscaOpcoes) (*lib.BuscaOpcoesResponse, error) {
	ret := _m.Called(BuscaOpcoes)

	var r0 *lib.BuscaOpcoesResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaOpcoes) *lib.BuscaOpcoesResponse); ok {
		r0 = rf(BuscaOpcoes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaOpcoesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaOpcoes) error); ok {
		r1 = rf(BuscaOpcoes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaPagamentoEntrega provides a mock function with given fields: BuscaPagamentoEntrega
func (_m *CorreiosSigepService) BuscaPagamentoEntrega(BuscaPagamentoEntrega *lib.BuscaPagamentoEntrega) (*lib.BuscaPagamentoEntregaResponse, error) {
	ret := _m.Called(BuscaPagamentoEntrega)

	var r0 *lib.BuscaPagamentoEntregaResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaPagamentoEntrega) *lib.BuscaPagamentoEntregaResponse); ok {
		r0 = rf(BuscaPagamentoEntrega)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaPagamentoEntregaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaPagamentoEntrega) error); ok {
		r1 = rf(BuscaPagamentoEntrega)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaServicos provides a mock function with given fields: BuscaServicos
func (_m *CorreiosSigepService) BuscaServicos(BuscaServicos *lib.BuscaServicos) (*lib.BuscaServicosResponse, error) {
	ret := _m.Called(BuscaServicos)

	var r0 *lib.BuscaServicosResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaServicos) *lib.BuscaServicosResponse); ok {
		r0 = rf(BuscaServicos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaServicosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaServicos) error); ok {
		r1 = rf(BuscaServicos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaServicosAdicionaisAtivos provides a mock function with given fields: BuscaServicosAdicionaisAtivos
func (_m *CorreiosSigepService) BuscaServicosAdicionaisAtivos(BuscaServicosAdicionaisAtivos *lib.BuscaServicosAdicionaisAtivos) (*lib.BuscaServicosAdicionaisAtivosResponse, error) {
	ret := _m.Called(BuscaServicosAdicionaisAtivos)

	var r0 *lib.BuscaServicosAdicionaisAtivosResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaServicosAdicionaisAtivos) *lib.BuscaServicosAdicionaisAtivosResponse); ok {
		r0 = rf(BuscaServicosAdicionaisAtivos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaServicosAdicionaisAtivosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaServicosAdicionaisAtivos) error); ok {
		r1 = rf(BuscaServicosAdicionaisAtivos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaServicosValorDeclarado provides a mock function with given fields: BuscaServicosValorDeclarado
func (_m *CorreiosSigepService) BuscaServicosValorDeclarado(BuscaServicosValorDeclarado *lib.BuscaServicosValorDeclarado) (*lib.BuscaServicosValorDeclaradoResponse, error) {
	ret := _m.Called(BuscaServicosValorDeclarado)

	var r0 *lib.BuscaServicosValorDeclaradoResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaServicosValorDeclarado) *lib.BuscaServicosValorDeclaradoResponse); ok {
		r0 = rf(BuscaServicosValorDeclarado)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaServicosValorDeclaradoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaServicosValorDeclarado) error); ok {
		r1 = rf(BuscaServicosValorDeclarado)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaServicosXServicosAdicionais provides a mock function with given fields: BuscaServicosXServicosAdicionais
func (_m *CorreiosSigepService) BuscaServicosXServicosAdicionais(BuscaServicosXServicosAdicionais *lib.BuscaServicosXServicosAdicionais) (*lib.BuscaServicosXServicosAdicionaisResponse, error) {
	ret := _m.Called(BuscaServicosXServicosAdicionais)

	var r0 *lib.BuscaServicosXServicosAdicionaisResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaServicosXServicosAdicionais) *lib.BuscaServicosXServicosAdicionaisResponse); ok {
		r0 = rf(BuscaServicosXServicosAdicionais)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaServicosXServicosAdicionaisResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaServicosXServicosAdicionais) error); ok {
		r1 = rf(BuscaServicosXServicosAdicionais)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaTarifaVale provides a mock function with given fields: BuscaTarifaVale
func (_m *CorreiosSigepService) BuscaTarifaVale(BuscaTarifaVale *lib.BuscaTarifaVale) (*lib.BuscaTarifaValeResponse, error) {
	ret := _m.Called(BuscaTarifaVale)

	var r0 *lib.BuscaTarifaValeResponse
	if rf, ok := ret.Get(0).(func(*lib.BuscaTarifaVale) *lib.BuscaTarifaValeResponse); ok {
		r0 = rf(BuscaTarifaVale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.BuscaTarifaValeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.BuscaTarifaVale) error); ok {
		r1 = rf(BuscaTarifaVale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculaTarifaServico provides a mock function with given fields: CalculaTarifaServico
func (_m *CorreiosSigepService) CalculaTarifaServico(CalculaTarifaServico *lib.CalculaTarifaServico) (*lib.CalculaTarifaServicoResponse, error) {
	ret := _m.Called(CalculaTarifaServico)

	var r0 *lib.CalculaTarifaServicoResponse
	if rf, ok := ret.Get(0).(func(*lib.CalculaTarifaServico) *lib.CalculaTarifaServicoResponse); ok {
		r0 = rf(CalculaTarifaServico)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.CalculaTarifaServicoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.CalculaTarifaServico) error); ok {
		r1 = rf(CalculaTarifaServico)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelarObjeto provides a mock function with given fields: CancelarObjeto
func (_m *CorreiosSigepService) CancelarObjeto(CancelarObjeto *lib.CancelarObjeto) (*lib.CancelarObjetoResponse, error) {
	ret := _m.Called(CancelarObjeto)

	var r0 *lib.CancelarObjetoResponse
	if rf, ok := ret.Get(0).(func(*lib.CancelarObjeto) *lib.CancelarObjetoResponse); ok {
		r0 = rf(CancelarObjeto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.CancelarObjetoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.CancelarObjeto) error); ok {
		r1 = rf(CancelarObjeto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelarPedidoScol provides a mock function with given fields: CancelarPedidoScol
func (_m *CorreiosSigepService) CancelarPedidoScol(CancelarPedidoScol *lib.CancelarPedidoScol) (*lib.CancelarPedidoScolResponse, error) {
	ret := _m.Called(CancelarPedidoScol)

	var r0 *lib.CancelarPedidoScolResponse
	if rf, ok := ret.Get(0).(func(*lib.CancelarPedidoScol) *lib.CancelarPedidoScolResponse); ok {
		r0 = rf(CancelarPedidoScol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.CancelarPedidoScolResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.CancelarPedidoScol) error); ok {
		r1 = rf(CancelarPedidoScol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsultaCEP provides a mock function with given fields: ConsultaCEP
func (_m *CorreiosSigepService) ConsultaCEP(ConsultaCEP *lib.ConsultaCEP) (*lib.ConsultaCEPResponse, error) {
	ret := _m.Called(ConsultaCEP)

	var r0 *lib.ConsultaCEPResponse
	if rf, ok := ret.Get(0).(func(*lib.ConsultaCEP) *lib.ConsultaCEPResponse); ok {
		r0 = rf(ConsultaCEP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ConsultaCEPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ConsultaCEP) error); ok {
		r1 = rf(ConsultaCEP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FechaPlp provides a mock function with given fields: FechaPlp
func (_m *CorreiosSigepService) FechaPlp(FechaPlp *lib.FechaPlp) (*lib.FechaPlpResponse, error) {
	ret := _m.Called(FechaPlp)

	var r0 *lib.FechaPlpResponse
	if rf, ok := ret.Get(0).(func(*lib.FechaPlp) *lib.FechaPlpResponse); ok {
		r0 = rf(FechaPlp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.FechaPlpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.FechaPlp) error); ok {
		r1 = rf(FechaPlp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FechaPlpVariosServicos provides a mock function with given fields: FechaPlpVariosServicos
func (_m *CorreiosSigepService) FechaPlpVariosServicos(FechaPlpVariosServicos *lib.FechaPlpVariosServicos) (*lib.FechaPlpVariosServicosResponse, error) {
	ret := _m.Called(FechaPlpVariosServicos)

	var r0 *lib.FechaPlpVariosServicosResponse
	if rf, ok := ret.Get(0).(func(*lib.FechaPlpVariosServicos) *lib.FechaPlpVariosServicosResponse); ok {
		r0 = rf(FechaPlpVariosServicos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.FechaPlpVariosServicosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.FechaPlpVariosServicos) error); ok {
		r1 = rf(FechaPlpVariosServicos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeraDigitoVerificadorEtiquetas provides a mock function with given fields: GeraDigitoVerificadorEtiquetas
func (_m *CorreiosSigepService) GeraDigitoVerificadorEtiquetas(GeraDigitoVerificadorEtiquetas *lib.GeraDigitoVerificadorEtiquetas) (*lib.GeraDigitoVerificadorEtiquetasResponse, error) {
	ret := _m.Called(GeraDigitoVerificadorEtiquetas)

	var r0 *lib.GeraDigitoVerificadorEtiquetasResponse
	if rf, ok := ret.Get(0).(func(*lib.GeraDigitoVerificadorEtiquetas) *lib.GeraDigitoVerificadorEtiquetasResponse); ok {
		r0 = rf(GeraDigitoVerificadorEtiquetas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.GeraDigitoVerificadorEtiquetasResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.GeraDigitoVerificadorEtiquetas) error); ok {
		r1 = rf(GeraDigitoVerificadorEtiquetas)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatusCartaoPostagem provides a mock function with given fields: GetStatusCartaoPostagem
func (_m *CorreiosSigepService) GetStatusCartaoPostagem(GetStatusCartaoPostagem *lib.GetStatusCartaoPostagem) (*lib.GetStatusCartaoPostagemResponse, error) {
	ret := _m.Called(GetStatusCartaoPostagem)

	var r0 *lib.GetStatusCartaoPostagemResponse
	if rf, ok := ret.Get(0).(func(*lib.GetStatusCartaoPostagem) *lib.GetStatusCartaoPostagemResponse); ok {
		r0 = rf(GetStatusCartaoPostagem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.GetStatusCartaoPostagemResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.GetStatusCartaoPostagem) error); ok {
		r1 = rf(GetStatusCartaoPostagem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatusPLP provides a mock function with given fields: GetStatusPLP
func (_m *CorreiosSigepService) GetStatusPLP(GetStatusPLP *lib.GetStatusPLP) (*lib.GetStatusPLPResponse, error) {
	ret := _m.Called(GetStatusPLP)

	var r0 *lib.GetStatusPLPResponse
	if rf, ok := ret.Get(0).(func(*lib.GetStatusPLP) *lib.GetStatusPLPResponse); ok {
		r0 = rf(GetStatusPLP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.GetStatusPLPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.GetStatusPLP) error); ok {
		r1 = rf(GetStatusPLP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntegrarUsuarioScol provides a mock function with given fields: IntegrarUsuarioScol
func (_m *CorreiosSigepService) IntegrarUsuarioScol(IntegrarUsuarioScol *lib.IntegrarUsuarioScol) (*lib.IntegrarUsuarioScolResponse, error) {
	ret := _m.Called(IntegrarUsuarioScol)

	var r0 *lib.IntegrarUsuarioScolResponse
	if rf, ok := ret.Get(0).(func(*lib.IntegrarUsuarioScol) *lib.IntegrarUsuarioScolResponse); ok {
		r0 = rf(IntegrarUsuarioScol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.IntegrarUsuarioScolResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.IntegrarUsuarioScol) error); ok {
		r1 = rf(IntegrarUsuarioScol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObterClienteAtualizacao provides a mock function with given fields: ObterClienteAtualizacao
func (_m *CorreiosSigepService) ObterClienteAtualizacao(ObterClienteAtualizacao *lib.ObterClienteAtualizacao) (*lib.ObterClienteAtualizacaoResponse, error) {
	ret := _m.Called(ObterClienteAtualizacao)

	var r0 *lib.ObterClienteAtualizacaoResponse
	if rf, ok := ret.Get(0).(func(*lib.ObterClienteAtualizacao) *lib.ObterClienteAtualizacaoResponse); ok {
		r0 = rf(ObterClienteAtualizacao)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ObterClienteAtualizacaoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ObterClienteAtualizacao) error); ok {
		r1 = rf(ObterClienteAtualizacao)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObterEmbalagemLRS provides a mock function with given fields: ObterEmbalagemLRS
func (_m *CorreiosSigepService) ObterEmbalagemLRS(ObterEmbalagemLRS *lib.ObterEmbalagemLRS) (*lib.ObterEmbalagemLRSResponse, error) {
	ret := _m.Called(ObterEmbalagemLRS)

	var r0 *lib.ObterEmbalagemLRSResponse
	if rf, ok := ret.Get(0).(func(*lib.ObterEmbalagemLRS) *lib.ObterEmbalagemLRSResponse); ok {
		r0 = rf(ObterEmbalagemLRS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ObterEmbalagemLRSResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ObterEmbalagemLRS) error); ok {
		r1 = rf(ObterEmbalagemLRS)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObterMensagemParametrizada provides a mock function with given fields: ObterMensagemParametrizada
func (_m *CorreiosSigepService) ObterMensagemParametrizada(ObterMensagemParametrizada *lib.ObterMensagemParametrizada) (*lib.ObterMensagemParametrizadaResponse, error) {
	ret := _m.Called(ObterMensagemParametrizada)

	var r0 *lib.ObterMensagemParametrizadaResponse
	if rf, ok := ret.Get(0).(func(*lib.ObterMensagemParametrizada) *lib.ObterMensagemParametrizadaResponse); ok {
		r0 = rf(ObterMensagemParametrizada)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ObterMensagemParametrizadaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ObterMensagemParametrizada) error); ok {
		r1 = rf(ObterMensagemParametrizada)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PesquisarDimensoesServico provides a mock function with given fields: PesquisarDimensoesServico
func (_m *CorreiosSigepService) PesquisarDimensoesServico(PesquisarDimensoesServico *lib.PesquisarDimensoesServico) (*lib.PesquisarDimensoesServicoResponse, error) {
	ret := _m.Called(PesquisarDimensoesServico)

	var r0 *lib.PesquisarDimensoesServicoResponse
	if rf, ok := ret.Get(0).(func(*lib.PesquisarDimensoesServico) *lib.PesquisarDimensoesServicoResponse); ok {
		r0 = rf(PesquisarDimensoesServico)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.PesquisarDimensoesServicoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.PesquisarDimensoesServico) error); ok {
		r1 = rf(PesquisarDimensoesServico)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PesquisarEmbalagensPorServico provides a mock function with given fields: PesquisarEmbalagensPorServico
func (_m *CorreiosSigepService) PesquisarEmbalagensPorServico(PesquisarEmbalagensPorServico *lib.PesquisarEmbalagensPorServico) (*lib.PesquisarEmbalagensPorServicoResponse, error) {
	ret := _m.Called(PesquisarEmbalagensPorServico)

	var r0 *lib.PesquisarEmbalagensPorServicoResponse
	if rf, ok := ret.Get(0).(func(*lib.PesquisarEmbalagensPorServico) *lib.PesquisarEmbalagensPorServicoResponse); ok {
		r0 = rf(PesquisarEmbalagensPorServico)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.PesquisarEmbalagensPorServicoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.PesquisarEmbalagensPorServico) error); ok {
		r1 = rf(PesquisarEmbalagensPorServico)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PesquisarParametrosPorDescricao provides a mock function with given fields: PesquisarParametrosPorDescricao
func (_m *CorreiosSigepService) PesquisarParametrosPorDescricao(PesquisarParametrosPorDescricao *lib.PesquisarParametrosPorDescricao) (*lib.PesquisarParametrosPorDescricaoResponse, error) {
	ret := _m.Called(PesquisarParametrosPorDescricao)

	var r0 *lib.PesquisarParametrosPorDescricaoResponse
	if rf, ok := ret.Get(0).(func(*lib.PesquisarParametrosPorDescricao) *lib.PesquisarParametrosPorDescricaoResponse); ok {
		r0 = rf(PesquisarParametrosPorDescricao)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.PesquisarParametrosPorDescricaoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.PesquisarParametrosPorDescricao) error); ok {
		r1 = rf(PesquisarParametrosPorDescricao)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PesquisarServicosAdicionais provides a mock function with given fields: PesquisarServicosAdicionais
func (_m *CorreiosSigepService) PesquisarServicosAdicionais(PesquisarServicosAdicionais *lib.PesquisarServicosAdicionais) (*lib.PesquisarServicosAdicionaisResponse, error) {
	ret := _m.Called(PesquisarServicosAdicionais)

	var r0 *lib.PesquisarServicosAdicionaisResponse
	if rf, ok := ret.Get(0).(func(*lib.PesquisarServicosAdicionais) *lib.PesquisarServicosAdicionaisResponse); ok {
		r0 = rf(PesquisarServicosAdicionais)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.PesquisarServicosAdicionaisResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.PesquisarServicosAdicionais) error); ok {
		r1 = rf(PesquisarServicosAdicionais)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SolicitaEtiquetas provides a mock function with given fields: SolicitaEtiquetas
func (_m *CorreiosSigepService) SolicitaEtiquetas(SolicitaEtiquetas *lib.SolicitaEtiquetas) (*lib.SolicitaEtiquetasResponse, error) {
	ret := _m.Called(SolicitaEtiquetas)

	var r0 *lib.SolicitaEtiquetasResponse
	if rf, ok := ret.Get(0).(func(*lib.SolicitaEtiquetas) *lib.SolicitaEtiquetasResponse); ok {
		r0 = rf(SolicitaEtiquetas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.SolicitaEtiquetasResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.SolicitaEtiquetas) error); ok {
		r1 = rf(SolicitaEtiquetas)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SolicitaPLP provides a mock function with given fields: SolicitaPLP
func (_m *CorreiosSigepService) SolicitaPLP(SolicitaPLP *lib.SolicitaPLP) (*lib.SolicitaPLPResponse, error) {
	ret := _m.Called(SolicitaPLP)

	var r0 *lib.SolicitaPLPResponse
	if rf, ok := ret.Get(0).(func(*lib.SolicitaPLP) *lib.SolicitaPLPResponse); ok {
		r0 = rf(SolicitaPLP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.SolicitaPLPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.SolicitaPLP) error); ok {
		r1 = rf(SolicitaPLP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SolicitaXmlPlp provides a mock function with given fields: SolicitaXmlPlp
func (_m *CorreiosSigepService) SolicitaXmlPlp(SolicitaXmlPlp *lib.SolicitaXmlPlp) (*lib.SolicitaXmlPlpResponse, error) {
	ret := _m.Called(SolicitaXmlPlp)

	var r0 *lib.SolicitaXmlPlpResponse
	if rf, ok := ret.Get(0).(func(*lib.SolicitaXmlPlp) *lib.SolicitaXmlPlpResponse); ok {
		r0 = rf(SolicitaXmlPlp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.SolicitaXmlPlpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.SolicitaXmlPlp) error); ok {
		r1 = rf(SolicitaXmlPlp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SolicitarPostagemScol provides a mock function with given fields: SolicitarPostagemScol
func (_m *CorreiosSigepService) SolicitarPostagemScol(SolicitarPostagemScol *lib.SolicitarPostagemScol) (*lib.SolicitarPostagemScolResponse, error) {
	ret := _m.Called(SolicitarPostagemScol)

	var r0 *lib.SolicitarPostagemScolResponse
	if rf, ok := ret.Get(0).(func(*lib.SolicitarPostagemScol) *lib.SolicitarPostagemScolResponse); ok {
		r0 = rf(SolicitarPostagemScol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.SolicitarPostagemScolResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.SolicitarPostagemScol) error); ok {
		r1 = rf(SolicitarPostagemScol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidaEtiquetaPLP provides a mock function with given fields: ValidaEtiquetaPLP
func (_m *CorreiosSigepService) ValidaEtiquetaPLP(ValidaEtiquetaPLP *lib.ValidaEtiquetaPLP) (*lib.ValidaEtiquetaPLPResponse, error) {
	ret := _m.Called(ValidaEtiquetaPLP)

	var r0 *lib.ValidaEtiquetaPLPResponse
	if rf, ok := ret.Get(0).(func(*lib.ValidaEtiquetaPLP) *lib.ValidaEtiquetaPLPResponse); ok {
		r0 = rf(ValidaEtiquetaPLP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ValidaEtiquetaPLPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ValidaEtiquetaPLP) error); ok {
		r1 = rf(ValidaEtiquetaPLP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidaPlp provides a mock function with given fields: ValidaPlp
func (_m *CorreiosSigepService) ValidaPlp(ValidaPlp *lib.ValidaPlp) (*lib.ValidaPlpResponse, error) {
	ret := _m.Called(ValidaPlp)

	var r0 *lib.ValidaPlpResponse
	if rf, ok := ret.Get(0).(func(*lib.ValidaPlp) *lib.ValidaPlpResponse); ok {
		r0 = rf(ValidaPlp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ValidaPlpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ValidaPlp) error); ok {
		r1 = rf(ValidaPlp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidarPostagemReversa provides a mock function with given fields: ValidarPostagemReversa
func (_m *CorreiosSigepService) ValidarPostagemReversa(ValidarPostagemReversa *lib.ValidarPostagemReversa) (*lib.ValidarPostagemReversaResponse, error) {
	ret := _m.Called(ValidarPostagemReversa)

	var r0 *lib.ValidarPostagemReversaResponse
	if rf, ok := ret.Get(0).(func(*lib.ValidarPostagemReversa) *lib.ValidarPostagemReversaResponse); ok {
		r0 = rf(ValidarPostagemReversa)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ValidarPostagemReversaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ValidarPostagemReversa) error); ok {
		r1 = rf(ValidarPostagemReversa)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidarPostagemSimultanea provides a mock function with given fields: ValidarPostagemSimultanea
func (_m *CorreiosSigepService) ValidarPostagemSimultanea(ValidarPostagemSimultanea *lib.ValidarPostagemSimultanea) (*lib.ValidarPostagemSimultaneaResponse, error) {
	ret := _m.Called(ValidarPostagemSimultanea)

	var r0 *lib.ValidarPostagemSimultaneaResponse
	if rf, ok := ret.Get(0).(func(*lib.ValidarPostagemSimultanea) *lib.ValidarPostagemSimultaneaResponse); ok {
		r0 = rf(ValidarPostagemSimultanea)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ValidarPostagemSimultaneaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.ValidarPostagemSimultanea) error); ok {
		r1 = rf(ValidarPostagemSimultanea)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificaDisponibilidadeServico provides a mock function with given fields: VerificaDisponibilidadeServico
func (_m *CorreiosSigepService) VerificaDisponibilidadeServico(VerificaDisponibilidadeServico *lib.VerificaDisponibilidadeServico) (*lib.VerificaDisponibilidadeServicoResponse, error) {
	ret := _m.Called(VerificaDisponibilidadeServico)

	var r0 *lib.VerificaDisponibilidadeServicoResponse
	if rf, ok := ret.Get(0).(func(*lib.VerificaDisponibilidadeServico) *lib.VerificaDisponibilidadeServicoResponse); ok {
		r0 = rf(VerificaDisponibilidadeServico)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.VerificaDisponibilidadeServicoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.VerificaDisponibilidadeServico) error); ok {
		r1 = rf(VerificaDisponibilidadeServico)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificaModalTransporte provides a mock function with given fields: VerificaModalTransporte
func (_m *CorreiosSigepService) VerificaModalTransporte(VerificaModalTransporte *lib.VerificaModalTransporte) (*lib.VerificaModalTransporteResponse, error) {
	ret := _m.Called(VerificaModalTransporte)

	var r0 *lib.VerificaModalTransporteResponse
	if rf, ok := ret.Get(0).(func(*lib.VerificaModalTransporte) *lib.VerificaModalTransporteResponse); ok {
		r0 = rf(VerificaModalTransporte)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.VerificaModalTransporteResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.VerificaModalTransporte) error); ok {
		r1 = rf(VerificaModalTransporte)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificaSeTodosObjetosCancelados provides a mock function with given fields: VerificaSeTodosObjetosCancelados
func (_m *CorreiosSigepService) VerificaSeTodosObjetosCancelados(VerificaSeTodosObjetosCancelados *lib.VerificaSeTodosObjetosCancelados) (*lib.VerificaSeTodosObjetosCanceladosResponse, error) {
	ret := _m.Called(VerificaSeTodosObjetosCancelados)

	var r0 *lib.VerificaSeTodosObjetosCanceladosResponse
	if rf, ok := ret.Get(0).(func(*lib.VerificaSeTodosObjetosCancelados) *lib.VerificaSeTodosObjetosCanceladosResponse); ok {
		r0 = rf(VerificaSeTodosObjetosCancelados)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.VerificaSeTodosObjetosCanceladosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lib.VerificaSeTodosObjetosCancelados) error); ok {
		r1 = rf(VerificaSeTodosObjetosCancelados)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
